import os

os.environ["BOT_TOKEN"] = ""
os.environ["WHITELIST"] = "[]"
os.environ["REPORTS_CHAT_ID"] = "100500"
os.environ["PERMANENT_BAN"] = "false"
os.environ["BAN_TIME"] = "35"
os.environ["COOLDOWN_TIME"] = "604800"
# os.environ["VALIDATOR_URL"] = "http://web-app:7777"
# os.environ["VALIDATOR_URL"] = "http://localhost:12345"
os.environ["VALIDATOR_URL"] = "https://f2be-195-211-193-160.ngrok-free.app/check"
os.environ["REDIS_HOST"] = "redis"
os.environ["REDIS_DB"] = "5"
os.environ["VALIDATOR_USER"] = "tg-spam"
os.environ["VALIDATOR_PASS"] = "123456789"
